apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: front-end
  name: myapp-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
