apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # securityContext:
      #   fsGroup: 472
      #   supplementalGroups:
      #     - 0
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 300m
              memory: 1000Mi
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: c0dexec
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          ports:
            - containerPort: 5432
              name: tcp-postgres
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc