# "apiVersion", "v1" is used for Pods
apiVersion: v1
# "kind" specifies the type of respource
kind: Pod
# "metadata" contains Pod details
metadata:
# Pod Name
  name: testpod
  namespace: alpha
# "spec" Contains container details which can be more than one
spec:
  containers:
    - name: test
      image: ubuntu
      command: ['sh', '-c','tail -f /dev/null']
    # "restartPolicy" set for the containers within "containers"
  restartPolicy: Never