apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: App1
    function: Front-end
  name: simple-webapp
spec:
  containers:
  - image: simple-webapp
    name: simple-webapp
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
