apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-sc
  annotations: storageclass.kubernetes.io/is-default-class=true
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.0.50
  share: /nfs-data
mountOptions:
  - nfsvers=4.1
