apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: reporting-cron-job
spec: # Cronjob spec
  jobTemplate: # Job template
    metadata:
      creationTimestamp: null
      name: reporting-cron-job
    spec: # Job spec
      completion: 3
      parallelism: 3
      template:
        metadata:
          creationTimestamp: null
        spec: # Pod spec
          containers:
          - image: ubuntu
            name: reporting-tool
            resources: {}
          restartPolicy: OnFailure
  schedule: '* /1 * * * *'
status: {}
