apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - image: nginx:alpine
    name: secret-pod
    resources: {}
    env:
      - name: fruit
        valueFrom:
          secretKeyRef:
            key: monkey
            name: secret-text
      - name: snack
        valueFrom:
          secretKeyRef:
            key: doggo
            name: secret-text
    envFrom:
      - secretRef:
          name: secret-text
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
