apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: my-pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        fsGroup: 5050
        supplementalGroups:
          - 5050
      containers:
        - name: pgadmin
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 300m
              memory: 1500Mi
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_LISTEN_PORT
              value: '80'
            - name: PGADMIN_DEFAULT_EMAIL
              value: asambhav@c0dexec.dev
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-pass
                  key: password
          ports:
            - containerPort: 80
              name: http-pgadmin
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
            initialDelaySeconds: 150
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 150
            periodSeconds: 50
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1