apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-prod  # Name of the ClusterIssuer
    kind: ClusterIssuer
  commonName: vault.c0dexec.dev
  dnsNames:
  - vault.c0dexec.dev
