---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
      - configmaps
      - pandas.awesome.bears.example
    providers:
      - aescbc:
          keys:
            - name: key1
              # See the following text for more details about the secret value
              secret: CtFuCTcMExGp6nVJlpqixznHXEn8kMzecfJ075LNT3k= 
      - identity: {} # this fallback allows reading unencrypted secrets;
                     # for example, during initial migration
