# "apiVersion", "v1" is used for Pods
apiVersion: v1
# "kind" specifies the type of respource
kind: Pod
# "metadata" contains Pod details
metadata:
  # Pod Name
  name: labelpod
  labels:
    # Its a "staging" pod
    environment: staging # Format "key: value"
    # Has "frontend" application as "tier"
    tier: frontend # Format "key: value"
# "spec" Contains container details which can be more than one
spec:
  containers:
    - name: labelcontainer
      image: nginx
      ports:
        - containerPort: 80