# "apiVersion", "v1" is used for Pods
apiVersion: v1
# "kind" specifies the type of respource
kind: Pod
# "metadata" contains Pod details
metadata:
  # Pod Name
  name: annopod
  annotations:
    k8slink: "https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/"
spec:
  containers:
    - name: labelcontainer
      image: nginx
      ports:
        - containerPort: 80
