apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-blue
    type: front-end
  name: myapp-blue
spec:
  replicas: 5
  selector:
    matchLabels:
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        version: v1
    spec:
      containers:
      - image: myapp-image:1.0
        name: myapp-image
        resources: {}
status: {}
