apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-primary
    type: front-end
  name: myapp-primary
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-end
        version: v1
    spec:
      containers:
      - image: myapp-image:1.0
        name: app-container
        resources: {}
status: {}
