apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constrant
spec:
  limits:
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max: # Maximum limit for the resource type in this case its "Container"
        cpu: "1"
        memory: 1Gi
      min: # Minimum limit for the resource type in this case its "Container"
        cpu: 100m
        memory: 500Mi
      type: Container 
