apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          #      tolerations:
          #      - key: "node-role.kubernetes.io/control-plane"
          #        operator: "Exists"
          #        effect: NoSchedule
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: my-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-nginx-svc
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
