apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple-webapp
  name: simple-webapp
spec:
  containers:
  - image: simple-webapp
    name: simple-webapp
    ports:
    - containerPort: 8080
    resources: {}
  livenessProbe:
    httpGet: 
      path: /api/healthy
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5 # Frequency at which probes requests are performed.
    failureThreshold: 7
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
