apiVersion: v1
kind: Pod
metadata:
  name: web-prod
spec:
  securityContext: # Pod specific
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1100 # Container specific, overwrites Pod Security Context with Container's
        capabilities:
          add: ["MAC_ADMIN"]
