apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-service
spec:
  ports:
  - name: 443-8080
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: front-end
  type: LoadBalancer
status:
  loadBalancer: {}
