apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-cert
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: letsencrypt-prod  # Name of the ClusterIssuer
    kind: ClusterIssuer
  commonName: argocd.c0dexec.dev
  dnsNames:
  - argocd.c0dexec.dev
