apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: container-vol
        mountPath: /usr/share/nginx/html
    resources: {}
  initContainers:
  - name: bb-init
    image: busybox
    command: ["/bin/sh", "-c", "wget -O /work-dir/index.html http://neverssl.com/online"]
    volumeMounts:
      - name: container-vol
        mountPath: /work-dir
  volumes:
  - name: container-vol
    emptyDir:
      sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
