apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: random-number-generator
  name: random-number-generator
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - shuf -i 0-100 -n 1 >> /opt/number.out
    image: alpine
    name: random-number-generator
    resources: {}
    volumeMounts:
      name: data-volume
      mountPath: /opt
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - hostPath:
      type: "Directory"
      path: /data
status: {}
