apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-service
  name: my-service
spec:
  ports:
  - port: 9376
    protocol: TCP
    targetPort: 80
  selector:
    app: App1
  type: NodePort
status:
  loadBalancer: {}
